apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.projname }}
  namespace: {{ .Values.namespace }}
spec:
  description: {{ .Values.appname }}
  sourceRepos:
  - git@github.com:NunoMars/iac-final.git
  destinations:
  - name: in-cluster
    namespace: {{ .Values.namespaceiaac }}
    server: https://kubernetes.default.svc