apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: {{ .Values.frontendlabel }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.frontendlabel }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.frontendlabel }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80