apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backendlabel }}
  namespace: {{ .Values.namespace }}
  labels: 
    app: {{ .Values.backendlabel }}
spec:
  selector:    
    app: {{ .Values.backendlabel }}
  type: ClusterIP
  ports:
  - name: "5000"
    port: 5000
    protocol: TCP
    targetPort: 5000
status:
  loadBalancer: {}
